[2020-06-23 09:25:11,080] [safety.py:824] [safety:sear_info] [ERROR]- 获取数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-23 09:28:00,942] [safety.py:824] [safety:sear_info] [ERROR]- 获取数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-23 09:28:07,523] [safety.py:824] [safety:sear_info] [ERROR]- 获取数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-23 09:31:05,100] [safety.py:824] [safety:sear_info] [ERROR]- 获取数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-23 10:13:24,035] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,036] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,036] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,036] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,036] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,036] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,141] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,141] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,141] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,141] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,141] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:13:24,141] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,729] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,729] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,729] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,730] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,814] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,814] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,814] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:34:19,814] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:35:52,711] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:35:52,711] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:35:52,711] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:35:52,828] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:35:52,828] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:35:52,829] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:36:27,997] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-23 10:36:28,084] [threaten.py:267] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
