[2020-06-24 09:29:56,651] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,651] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,652] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,652] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,652] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,653] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,653] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:30:14,209] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:30:14,209] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 11:06:07,270] [monit.py:2832] [monit:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
